import React, {useState, useEffect} from 'react';
import {Loader, Card} from '../Components';

const RenderCards = ({data, title}) => {
    console.log("AL", data)
    if(data.length > 0) {
        return data.map((post) => (
            <Card key={post._id} name={post.name} prompt={post.prompt} photo={post.photo}/>
        ))
    }
     return (
        <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
     )
}

const Home = () => {

    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState([
        {
          _id: "64f454af48e96c96150cc441",
          name: "Govind",
          prompt: "AI Dog Image",
          photo: "https://img.freepik.com/free-photo/puppy-that-is-walking-snow_1340-37228.jpg"
        },
        {
          _id: "64f454af48e96c96150cc442",
          name: "John",
          prompt: "2 Dogs smiling",
          photo: "https://img.rawpixel.com/private/static/images/website/2022-05/ns8230-image.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=b3961e17298745c0868eeef46211c3d0"
        },
        {
            _id: "64f454af48e96c96150cc443",
            name: "Jinse",
            prompt: "Starry Night Face",
            photo: "https://img.freepik.com/premium-photo/creative-ai-generated-illustration-futuristic-woman-with-bright-makeup-starry-night-sky-hair-looking-camera_501669-25254.jpg?w=2000"
          },
          {
            _id: "64f454af48e96c96150cc444",
            name: "Kevin",
            prompt: "Night Sky",
            photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTdL_5_cw3GUkpa5IDgt_rdwcyAx85zDr2tw&usqp=CAU"
          },
          {
            _id: "64f454af48e96c96150cc445",
            name: "Lance",
            prompt: "Robot Face",
            photo: "https://as1.ftcdn.net/v2/jpg/05/77/04/14/1000_F_577041412_9A0YnuYIe5oSNSjWMuYwmzjw7vGqXq69.jpg"
          }
      ]);

    const fetchPosts = async () => {
        setLoading(true);
    
        try {
          const response = await fetch('http://localhost:8080/api/v1/post', {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
            },
          });
    
          if (response.ok) {
            const result = await response.json();
            setAllPosts(result.data.reverse());
          }
        } catch (err) {
          alert(err);
        } finally {
          setLoading(false);
        }
      };
    
      useEffect(() => {
       // fetchPosts();
      }, []);

  return (
    <section className="max-w-7xl mx-auto">
        <div>
            <h1 className="font-extrabold text-[#22328] text-[32px]">The Community ShowCase</h1>
            <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px] ">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
        </div>

        <div className="mt-10">
            {loading ? (
                <div className="flex justify-center items-center"><Loader/></div>
            ): (
                <>
                    <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                            <RenderCards data={allPosts} title="The Collection" />
                    </div>
                </>
            )}
        </div>
    </section>
  )
}

export default Home